---
# cusom opts for config file
prometheus_alertmanager_templates_path: /etc/prometheus/am-templates
prometheus_alertmanager_defaults_file: /etc/default/alertmanager
prometheus_alertmanager_resolve_timeout: 5m
prometheus_alertmanager_use_slack_tmpl: true
prometheus_alertmanager_routes: ''

# SMTP default params
prometheus_alertmanager_smtp_from: ''
prometheus_alertmanager_smtp_smarthost: ''
prometheus_alertmanager_smtp_auth_username: ''
prometheus_alertmanager_smtp_auth_password: ''
prometheus_alertmanager_smtp_auth_secret: ''
# Default values you can see here -> https://prometheus.io/docs/alerting/configuration/
prometheus_alertmanager_slack_api_url: ''
prometheus_alertmanager_victorops_api_key: ''
prometheus_alertmanager_victorops_api_url: ''
prometheus_alertmanager_pagerduty_url: ''
prometheus_alertmanager_opsgenie_api_host: ''
prometheus_alertmanager_hipchat_url: ''
prometheus_alertmanager_hipchat_auth_token: ''

prometheus_alertmanager_default_receiever: ''
prometheus_alertmanager_recievers:
  receivers:
    - name: 'slack'
      slack_configs:
      - channel: '#your_channel'
        send_resolved: true
        api_url: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXTJoXXXXXXXXX
prometheus_alertmanager_routes:
  route:
    group_by: [ 'alertname', 'cluster', 'service' ]
    group_wait: 30s
    group_interval: 5m
    receiver: slack
prometheus_alertmanager_inhibit_rules: ''

prometheus_alertmanager_opt_resolve_timeout:
prometheus_alertmanager_opt_protocol: http # http/https
prometheus_alertmanager_opt_port: 9093
prometheus_alertmanager_opt_listen_ip: '0.0.0.0'
prometheus_alertmanager_opt_web_listen_address: '{{ prometheus_alertmanager_opt_listen_ip }}:{{ prometheus_alertmanager_opt_port }}'

# official commandline args
prometheus_alertmanager_config_file: /etc/prometheus/alertmanager.yml
# how long to keep data for. (default 120h0m0s)
# prometheus_alertmanager_data_retention:
# value example: "logger:syslog?appname=bob&local=7" or "logger:stdout?json=true" (default "logger:stderr")
prometheus_alertmanager_log_format: "logger:syslog?appname=alertmanager&local=7"
# valid levels: [debug, info, warn, error, fatal] (default "info")
prometheus_alertmanager_log_level: info
# prometheus_alertmanager_mesh_listen_address:
# prometheus_alertmanager_mesh_nickname:
# prometheus_alertmanager_mesh_password:
# prometheus_alertmanager_mesh_peer:
# prometheus_alertmanager_mesh_peer_id:
prometheus_alertmanager_storage_path: /var/lib/prometheus/alertmanager
prometheus_alertmanager_web_external_url: '{{ prometheus_alertmanager_opt_web_listen_address }}'
prometheus_alertmanager_web_listen_address:
prometheus_alertmanager_web_route_prefix: '{{ prometheus_alertmanager_web_external_url }}'




prometheus_alertmanager_pre2_opts:
  - "web.listen-address={{ prometheus_alertmanager_opt_web_listen_address }}"
  - "log.format={{ prometheus_alertmanager_log_format | default(omit) }}"
  - "log.level={{ prometheus_alertmanager_log_level }}"

prometheus_alertmanager_opts:
  - "web.listen-address={{ prometheus_alertmanager_opt_web_listen_address }}"
  - "log.level={{ prometheus_alertmanager_log_level }}"
