---
# listen on all ipv4 (&v6) interfaces
prometheus_opt_listen_ip: '0.0.0.0'
prometheus_opt_web_listen_address: '{{ prometheus_opt_listen_ip }}:{{ prometheus_opt_port }}'
prometheus_opt_storage_local_dirty: false
prometheus_opt_storage_local_target_heap_size: '3221225472'
prometheus_opt_storage_local_retention: "720h" # 1month

prometheus_pre2_opts:
  - "web.listen-address={{ prometheus_opt_web_listen_address }}"
  - "log.level={{ prometheus_opt_log_level }}"
  - "log.format={{ prometheus_opt_log_format }}"
  - "alertmanager.url={{ prometheus_opt_alertmanager_url }}"
  - "web.external-url=http://{{ ansible_all_ipv4_addresses[0] }}:{{ prometheus_opt_port }}"
  - "storage.local.dirty={{ prometheus_opt_storage_local_dirty }}"
  - "storage.local.target-heap-size={{ prometheus_opt_storage_local_target_heap_size }}"
  - "storage.local.retention={{ prometheus_opt_storage_local_retention }}"

prometheus_opts:
  - "web.listen-address={{ prometheus_opt_web_listen_address }}"
  - "log.level={{ prometheus_opt_log_level }}"
  - "web.external-url=http://{{ ansible_all_ipv4_addresses[0] }}:{{ prometheus_opt_port }}"


prometheus_rule_files: ''
prometheus_file_sd_config_path: "{{ prometheus_conf_dir }}/jobs"
